"""Initial BFF, conversation, execution, artifact and notification schema."""

import sqlalchemy as sa
from alembic import op

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    """Create the current application schema in an empty database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artifacts",
        sa.Column("artifact_id", sa.String(length=128), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("subject_id", sa.String(length=128), nullable=False),
        sa.Column("content_type", sa.String(length=200), nullable=False),
        sa.Column("storage_uri", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.String(length=128), nullable=False),
        sa.Column("access_policy", sa.JSON(), nullable=False),
        sa.Column("encryption_metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("artifact_id"),
    )
    op.create_index(
        "ix_artifacts_owner", "artifacts", ["tenant_id", "subject_id", "artifact_id"], unique=False
    )
    op.create_table(
        "audit_records",
        sa.Column("audit_id", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("subject_id", sa.String(length=128), nullable=False),
        sa.Column("conversation_id", sa.String(length=128), nullable=True),
        sa.Column("turn_id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("tool_call_id", sa.String(length=128), nullable=True),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=128), nullable=False),
        sa.Column("resource_version", sa.String(length=32), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("decision", sa.String(length=64), nullable=False),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("evidence_refs", sa.JSON(), nullable=False),
        sa.Column("artifact_refs", sa.JSON(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("audit_id"),
    )
    op.create_index(
        "ix_audit_owner_time",
        "audit_records",
        ["tenant_id", "subject_id", "occurred_at"],
        unique=False,
    )
    op.create_index("ix_audit_run", "audit_records", ["run_id", "event_type"], unique=False)
    op.create_table(
        "conversations",
        sa.Column("conversation_id", sa.String(length=128), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("subject_id", sa.String(length=128), nullable=False),
        sa.Column("agent_id", sa.String(length=128), nullable=False),
        sa.Column("agent_profile_version", sa.String(length=32), nullable=False),
        sa.Column("agent_thread_id", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("conversation_id"),
        sa.UniqueConstraint("agent_thread_id", name="uq_conversations_agent_thread"),
    )
    op.create_index(
        "ix_conversations_owner",
        "conversations",
        ["tenant_id", "subject_id", "conversation_id"],
        unique=False,
    )
    op.create_table(
        "notification_senders",
        sa.Column("worker_id", sa.String(length=128), nullable=False),
        sa.Column("app_id", sa.String(length=128), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("worker_id"),
    )
    op.create_index(
        op.f("ix_notification_senders_app_id"), "notification_senders", ["app_id"], unique=False
    )
    op.create_table(
        "outbox_events",
        sa.Column("event_id", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("aggregate_type", sa.String(length=64), nullable=False),
        sa.Column("aggregate_id", sa.String(length=128), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("subject_id", sa.String(length=128), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        "ix_outbox_delivery",
        "outbox_events",
        ["status", "available_at", "locked_until"],
        unique=False,
    )
    op.create_index(
        "ix_outbox_owner", "outbox_events", ["tenant_id", "subject_id", "created_at"], unique=False
    )
    op.create_table(
        "run_control",
        sa.Column("control_id", sa.Integer(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("bff_admission_enabled", sa.Boolean(), nullable=False),
        sa.Column("bff_dispatch_paused", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("control_id"),
    )
    op.create_table(
        "run_executions",
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("root_run_id", sa.String(length=128), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("server_run_id", sa.String(length=128), nullable=True),
        sa.Column("waiting", sa.JSON(), nullable=True),
        sa.Column("cancellation_requested", sa.Boolean(), nullable=False),
        sa.Column("cancellation_confirmed", sa.Boolean(), nullable=False),
        sa.Column("side_effects_denied", sa.Boolean(), nullable=False),
        sa.Column("model_calls", sa.Integer(), nullable=False),
        sa.Column("tool_calls", sa.Integer(), nullable=False),
        sa.Column("operation_calls", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("root_run_id = run_id", name="ck_execution_is_root"),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_index(
        op.f("ix_run_executions_root_run_id"), "run_executions", ["root_run_id"], unique=False
    )
    op.create_table(
        "channel_conversation_bindings",
        sa.Column("binding_id", sa.String(length=128), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("app_id", sa.String(length=128), nullable=False),
        sa.Column("tenant_key", sa.String(length=128), nullable=False),
        sa.Column("external_user_id", sa.String(length=128), nullable=False),
        sa.Column("external_chat_id", sa.String(length=128), nullable=False),
        sa.Column("conversation_id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.conversation_id"],
        ),
        sa.PrimaryKeyConstraint("binding_id"),
        sa.UniqueConstraint(
            "channel",
            "app_id",
            "tenant_key",
            "external_chat_id",
            name="uq_channel_conversation_bindings_chat",
        ),
    )
    op.create_index(
        "ix_channel_conversation_bindings_user",
        "channel_conversation_bindings",
        ["channel", "app_id", "tenant_key", "external_user_id"],
        unique=False,
    )
    op.create_table(
        "conversation_summaries",
        sa.Column("summary_id", sa.String(length=128), nullable=False),
        sa.Column("conversation_id", sa.String(length=128), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("start_sequence", sa.Integer(), nullable=False),
        sa.Column("end_sequence", sa.Integer(), nullable=False),
        sa.Column("source_message_ids", sa.JSON(), nullable=False),
        sa.Column("source_summary_ids", sa.JSON(), nullable=False),
        sa.Column("summary_content", sa.Text(), nullable=False),
        sa.Column("topics", sa.JSON(), nullable=False),
        sa.Column("entities", sa.JSON(), nullable=False),
        sa.Column("decisions", sa.JSON(), nullable=False),
        sa.Column("open_items", sa.JSON(), nullable=False),
        sa.Column("model_profile_version", sa.String(length=32), nullable=False),
        sa.Column("template_version", sa.String(length=64), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("superseded_by", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.conversation_id"],
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by"],
            ["conversation_summaries.summary_id"],
        ),
        sa.PrimaryKeyConstraint("summary_id"),
    )
    op.create_index(
        "ix_summaries_conversation_range",
        "conversation_summaries",
        ["conversation_id", "level", "start_sequence", "end_sequence"],
        unique=False,
    )
    op.create_table(
        "conversation_turns",
        sa.Column("turn_id", sa.String(length=128), nullable=False),
        sa.Column("conversation_id", sa.String(length=128), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("subject_id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("server_run_id", sa.String(length=128), nullable=True),
        sa.Column("client_idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=False),
        sa.Column("target_id", sa.String(length=128), nullable=False),
        sa.Column("target_version", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.conversation_id"],
        ),
        sa.PrimaryKeyConstraint("turn_id"),
        sa.UniqueConstraint("run_id", name="uq_conversation_turns_run"),
        sa.UniqueConstraint(
            "tenant_id",
            "subject_id",
            "client_idempotency_key",
            name="uq_conversation_turns_owner_idempotency",
        ),
    )
    op.create_index(
        "ix_conversation_turns_conversation_created",
        "conversation_turns",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "pending_interactions",
        sa.Column("interaction_id", sa.String(length=128), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("subject_id", sa.String(length=128), nullable=False),
        sa.Column("conversation_id", sa.String(length=128), nullable=True),
        sa.Column("root_run_id", sa.String(length=128), nullable=False),
        sa.Column("owner_run_id", sa.String(length=128), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("thread_id", sa.String(length=128), nullable=False),
        sa.Column("server_run_id", sa.String(length=128), nullable=False),
        sa.Column("interrupt_id", sa.String(length=128), nullable=False),
        sa.Column("checkpoint_id", sa.String(length=128), nullable=True),
        sa.Column("point_id", sa.String(length=128), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("request", sa.JSON(), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by", sa.String(length=128), nullable=True),
        sa.Column("response_key", sa.String(length=256), nullable=True),
        sa.Column("response_hash", sa.String(length=64), nullable=True),
        sa.Column("response", sa.JSON(), nullable=True),
        sa.Column("operation_id", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_run_id"],
            ["run_executions.run_id"],
        ),
        sa.PrimaryKeyConstraint("interaction_id"),
    )
    op.create_index(
        op.f("ix_pending_interactions_owner_run_id"),
        "pending_interactions",
        ["owner_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pending_interactions_root_run_id"),
        "pending_interactions",
        ["root_run_id"],
        unique=False,
    )
    op.create_index(
        "uq_interactions_pending_root",
        "pending_interactions",
        ["root_run_id"],
        unique=True,
        sqlite_where=sa.text("status = 'pending'"),
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_table(
        "root_runs",
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("conversation_id", sa.String(length=128), nullable=False),
        sa.Column("backend_instance_id", sa.String(length=128), nullable=False),
        sa.Column("driver_version", sa.Integer(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("projection", sa.JSON(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("wake", sa.Integer(), nullable=False),
        sa.Column("epoch", sa.Integer(), nullable=False),
        sa.Column("owner", sa.String(length=128), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failures", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.conversation_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run_executions.run_id"],
        ),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_index(
        "ix_bff_driver_due",
        "root_runs",
        ["driver_version", "backend_instance_id", "active", "due_at"],
        unique=False,
    )
    op.create_index(
        "ix_root_due", "root_runs", ["backend_instance_id", "active", "due_at"], unique=False
    )
    op.create_index(
        "uq_root_active_conversation",
        "root_runs",
        ["conversation_id"],
        unique=True,
        sqlite_where=sa.text("active = 1"),
        postgresql_where=sa.text("active = true"),
    )
    op.create_table(
        "run_authorizations",
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("scopes", sa.JSON(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run_executions.run_id"],
        ),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_table(
        "run_operations",
        sa.Column("operation_id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("request", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("server_run_id", sa.String(length=128), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run_executions.run_id"],
        ),
        sa.PrimaryKeyConstraint("operation_id"),
    )
    op.create_index(op.f("ix_run_operations_run_id"), "run_operations", ["run_id"], unique=False)
    op.create_table(
        "backend_attempts",
        sa.Column("operation_id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("backend_instance_id", sa.String(length=128), nullable=False),
        sa.Column("execution_hash", sa.String(length=64), nullable=False),
        sa.Column("reference", sa.JSON(), nullable=False),
        sa.Column("cancellation_confirmed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["run_operations.operation_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["root_runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("operation_id"),
    )
    op.create_index(
        op.f("ix_backend_attempts_run_id"), "backend_attempts", ["run_id"], unique=False
    )
    op.create_index(
        "uq_backend_attempt_identity",
        "backend_attempts",
        ["backend_instance_id", "execution_hash"],
        unique=True,
    )
    op.create_table(
        "conversation_messages",
        sa.Column("message_id", sa.String(length=128), nullable=False),
        sa.Column("conversation_id", sa.String(length=128), nullable=False),
        sa.Column("turn_id", sa.String(length=128), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("parent_message_id", sa.String(length=128), nullable=True),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("visible", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.conversation_id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_message_id"],
            ["conversation_messages.message_id"],
        ),
        sa.ForeignKeyConstraint(
            ["turn_id"],
            ["conversation_turns.turn_id"],
        ),
        sa.PrimaryKeyConstraint("message_id"),
        sa.UniqueConstraint(
            "conversation_id", "sequence", name="uq_messages_conversation_sequence"
        ),
    )
    op.create_index(
        "ix_messages_turn_role", "conversation_messages", ["turn_id", "role"], unique=False
    )
    op.create_index(
        "uq_messages_final_assistant",
        "conversation_messages",
        ["turn_id"],
        unique=True,
        sqlite_where=sa.text("role = 'assistant' AND parent_message_id IS NULL"),
        postgresql_where=sa.text("role = 'assistant' AND parent_message_id IS NULL"),
    )
    op.create_table(
        "model_context_manifests",
        sa.Column("manifest_id", sa.String(length=128), nullable=False),
        sa.Column("model_call_id", sa.String(length=128), nullable=False),
        sa.Column("conversation_id", sa.String(length=128), nullable=False),
        sa.Column("turn_id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("prompt_template_version", sa.String(length=64), nullable=False),
        sa.Column("agent_profile_version", sa.String(length=32), nullable=False),
        sa.Column("model_profile_version", sa.String(length=32), nullable=False),
        sa.Column("recent_message_start", sa.Integer(), nullable=True),
        sa.Column("recent_message_end", sa.Integer(), nullable=True),
        sa.Column("summary_ids", sa.JSON(), nullable=False),
        sa.Column("memory_ids", sa.JSON(), nullable=False),
        sa.Column("memory_refs", sa.JSON(), nullable=False),
        sa.Column("historical_message_ids", sa.JSON(), nullable=False),
        sa.Column("tool_result_refs", sa.JSON(), nullable=False),
        sa.Column("exposed_tools", sa.JSON(), nullable=False),
        sa.Column("input_token_count", sa.Integer(), nullable=False),
        sa.Column("available_input_tokens", sa.Integer(), nullable=False),
        sa.Column("omissions", sa.JSON(), nullable=False),
        sa.Column("context_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.conversation_id"],
        ),
        sa.ForeignKeyConstraint(
            ["turn_id"],
            ["conversation_turns.turn_id"],
        ),
        sa.PrimaryKeyConstraint("manifest_id"),
        sa.UniqueConstraint("model_call_id", name="uq_manifests_model_call"),
    )
    op.create_index(
        "ix_manifests_run",
        "model_context_manifests",
        ["conversation_id", "turn_id", "run_id"],
        unique=False,
    )
    op.create_table(
        "notification_targets",
        sa.Column("target_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("binding_id", sa.String(length=128), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("subject_id", sa.String(length=128), nullable=False),
        sa.Column("app_id", sa.String(length=128), nullable=False),
        sa.Column("address", sa.JSON(), nullable=False),
        sa.Column("delivery_mode", sa.String(length=32), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["binding_id"],
            ["channel_conversation_bindings.binding_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run_executions.run_id"],
        ),
        sa.PrimaryKeyConstraint("target_id"),
        sa.UniqueConstraint("run_id"),
    )
    op.create_index(
        op.f("ix_notification_targets_app_id"), "notification_targets", ["app_id"], unique=False
    )
    op.create_table(
        "run_inbox",
        sa.Column("inbox_id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=True),
        sa.Column("backend_instance_id", sa.String(length=128), nullable=False),
        sa.Column("execution_hash", sa.String(length=64), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["root_runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("inbox_id"),
    )
    op.create_index(
        "ix_run_inbox_binding",
        "run_inbox",
        ["backend_instance_id", "execution_hash", "processed"],
        unique=False,
    )
    op.create_index("ix_run_inbox_expiry", "run_inbox", ["expires_at"], unique=False)
    op.create_index("ix_run_inbox_root", "run_inbox", ["run_id", "processed"], unique=False)
    op.create_table(
        "run_progress_events",
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["root_runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("run_id", "revision"),
    )
    op.create_table(
        "notification_events",
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("target_id", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("materialized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["notification_targets.target_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        "ix_notification_events_pending",
        "notification_events",
        ["materialized_at", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_events_target_id"), "notification_events", ["target_id"], unique=False
    )
    op.create_table(
        "notification_deliveries",
        sa.Column("delivery_id", sa.String(length=64), nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("part", sa.Integer(), nullable=False),
        sa.Column("parts", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("content_version", sa.Integer(), nullable=False),
        sa.Column("send_key", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("failures", sa.Integer(), nullable=False),
        sa.Column("uncertain", sa.Boolean(), nullable=False),
        sa.Column("owner", sa.String(length=128), nullable=True),
        sa.Column("epoch", sa.Integer(), nullable=False),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recover_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recovery_evidence_hash", sa.String(length=64), nullable=True),
        sa.Column("message_id", sa.String(length=128), nullable=True),
        sa.Column("error_class", sa.String(length=64), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["notification_events.event_id"],
        ),
        sa.PrimaryKeyConstraint("delivery_id"),
        sa.UniqueConstraint("send_key"),
    )
    op.create_index(
        "ix_notification_deliveries_due",
        "notification_deliveries",
        ["due_at", "lease_until"],
        unique=False,
    )
    op.create_index(
        "uq_notification_delivery_part",
        "notification_deliveries",
        ["event_id", "part"],
        unique=True,
    )
    # ### end Alembic commands ###
    op.execute(
        sa.text(
            "INSERT INTO run_control "
            "(control_id, revision, bff_admission_enabled, bff_dispatch_paused, updated_at) "
            "VALUES (1, 0, false, false, CURRENT_TIMESTAMP)"
        )
    )


def downgrade():
    """Drop the application schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_notification_delivery_part", table_name="notification_deliveries")
    op.drop_index("ix_notification_deliveries_due", table_name="notification_deliveries")
    op.drop_table("notification_deliveries")
    op.drop_index(op.f("ix_notification_events_target_id"), table_name="notification_events")
    op.drop_index("ix_notification_events_pending", table_name="notification_events")
    op.drop_table("notification_events")
    op.drop_table("run_progress_events")
    op.drop_index("ix_run_inbox_root", table_name="run_inbox")
    op.drop_index("ix_run_inbox_expiry", table_name="run_inbox")
    op.drop_index("ix_run_inbox_binding", table_name="run_inbox")
    op.drop_table("run_inbox")
    op.drop_index(op.f("ix_notification_targets_app_id"), table_name="notification_targets")
    op.drop_table("notification_targets")
    op.drop_index("ix_manifests_run", table_name="model_context_manifests")
    op.drop_table("model_context_manifests")
    op.drop_index(
        "uq_messages_final_assistant",
        table_name="conversation_messages",
        sqlite_where=sa.text("role = 'assistant' AND parent_message_id IS NULL"),
        postgresql_where=sa.text("role = 'assistant' AND parent_message_id IS NULL"),
    )
    op.drop_index("ix_messages_turn_role", table_name="conversation_messages")
    op.drop_table("conversation_messages")
    op.drop_index("uq_backend_attempt_identity", table_name="backend_attempts")
    op.drop_index(op.f("ix_backend_attempts_run_id"), table_name="backend_attempts")
    op.drop_table("backend_attempts")
    op.drop_index(op.f("ix_run_operations_run_id"), table_name="run_operations")
    op.drop_table("run_operations")
    op.drop_table("run_authorizations")
    op.drop_index(
        "uq_root_active_conversation",
        table_name="root_runs",
        sqlite_where=sa.text("active = 1"),
        postgresql_where=sa.text("active = true"),
    )
    op.drop_index("ix_root_due", table_name="root_runs")
    op.drop_index("ix_bff_driver_due", table_name="root_runs")
    op.drop_table("root_runs")
    op.drop_index(
        "uq_interactions_pending_root",
        table_name="pending_interactions",
        sqlite_where=sa.text("status = 'pending'"),
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index(op.f("ix_pending_interactions_root_run_id"), table_name="pending_interactions")
    op.drop_index(op.f("ix_pending_interactions_owner_run_id"), table_name="pending_interactions")
    op.drop_table("pending_interactions")
    op.drop_index("ix_conversation_turns_conversation_created", table_name="conversation_turns")
    op.drop_table("conversation_turns")
    op.drop_index("ix_summaries_conversation_range", table_name="conversation_summaries")
    op.drop_table("conversation_summaries")
    op.drop_index(
        "ix_channel_conversation_bindings_user", table_name="channel_conversation_bindings"
    )
    op.drop_table("channel_conversation_bindings")
    op.drop_index(op.f("ix_run_executions_root_run_id"), table_name="run_executions")
    op.drop_table("run_executions")
    op.drop_table("run_control")
    op.drop_index("ix_outbox_owner", table_name="outbox_events")
    op.drop_index("ix_outbox_delivery", table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_index(op.f("ix_notification_senders_app_id"), table_name="notification_senders")
    op.drop_table("notification_senders")
    op.drop_index("ix_conversations_owner", table_name="conversations")
    op.drop_table("conversations")
    op.drop_index("ix_audit_run", table_name="audit_records")
    op.drop_index("ix_audit_owner_time", table_name="audit_records")
    op.drop_table("audit_records")
    op.drop_index("ix_artifacts_owner", table_name="artifacts")
    op.drop_table("artifacts")
    # ### end Alembic commands ###
