"""Harness 的业务无关公共协议。

其他模块应从本包顶层导入稳定类型，不依赖内部文件布局。
"""

from .approval import (
    ApprovalDecision,
    ApprovalDecisionType,
    ApprovalGrant,
    ApprovalRequest,
)
from .base import ContractModel, JsonPrimitive, JsonValue, MutableContractModel
from .capability import (
    CapabilityDescriptor,
    CapabilityExecutionProfile,
    CapabilityType,
    EgressType,
    IdempotencyType,
    SideEffectType,
)
from .context import (
    CancellationContext,
    ExecutionState,
    ExecutionStatus,
    IdentityContext,
    InvocationContext,
    TenantContext,
    TraceContext,
)
from .errors import (
    CapabilityError,
    ErrorCategory,
    ErrorCode,
    ErrorDetail,
    HarnessError,
    HarnessTimeoutError,
    PlannerNotApplicableError,
    PlanningError,
    PluginError,
    PolicyError,
    ProviderError,
    RegistryError,
    RequestError,
    RoutingError,
    SelectionError,
)
from .execution import (
    NodeExecutionState,
    NodeExecutionStatus,
    PlanExecutionState,
    PlanExecutionStatus,
)
from .persistence import PlanExecutionRecord
from .plan import (
    BindingKind,
    ConditionExpr,
    ConditionOperator,
    EdgeTrigger,
    ExecutionPlan,
    FailurePolicy,
    InputBinding,
    LiteralBinding,
    NodeOutputBinding,
    OutputBinding,
    PlanBudget,
    PlanEdge,
    PlanNode,
    PlanNodeKind,
    RequestBinding,
    RetryPolicy,
    ValueReference,
)
from .provider import (
    ProviderAttempt,
    ProviderAttemptStatus,
    ProviderDescriptor,
    ProviderHealthSnapshot,
    ProviderHealthStatus,
    ProviderPin,
)
from .request import Request, RequestInput, RequestOptions, RequestTarget
from .result import Continuation, ResultEnvelope, ResultIssue, ResultOutput, ResultStatus
from .routing import ExecutionMode, RouteDecision, RouteSource, RouteType
from .selection import SelectionContext, SelectionDecision, SelectionRejection

__all__ = [
    "ApprovalDecision",
    "ApprovalDecisionType",
    "ApprovalGrant",
    "ApprovalRequest",
    "BindingKind",
    "CancellationContext",
    "CapabilityDescriptor",
    "CapabilityExecutionProfile",
    "CapabilityError",
    "CapabilityType",
    "ConditionExpr",
    "ConditionOperator",
    "Continuation",
    "ContractModel",
    "EdgeTrigger",
    "EgressType",
    "ErrorCategory",
    "ErrorCode",
    "ErrorDetail",
    "ExecutionState",
    "ExecutionStatus",
    "ExecutionPlan",
    "ExecutionMode",
    "FailurePolicy",
    "HarnessError",
    "HarnessTimeoutError",
    "IdentityContext",
    "IdempotencyType",
    "InputBinding",
    "InvocationContext",
    "JsonPrimitive",
    "JsonValue",
    "LiteralBinding",
    "MutableContractModel",
    "NodeExecutionState",
    "NodeExecutionStatus",
    "NodeOutputBinding",
    "OutputBinding",
    "PlanBudget",
    "PlanEdge",
    "PlanExecutionState",
    "PlanExecutionRecord",
    "PlanExecutionStatus",
    "PlanNode",
    "PlanNodeKind",
    "PlannerNotApplicableError",
    "PlanningError",
    "PluginError",
    "PolicyError",
    "ProviderAttempt",
    "ProviderAttemptStatus",
    "ProviderDescriptor",
    "ProviderError",
    "ProviderHealthSnapshot",
    "ProviderHealthStatus",
    "ProviderPin",
    "RegistryError",
    "Request",
    "RequestBinding",
    "RequestError",
    "RequestInput",
    "RequestOptions",
    "RequestTarget",
    "ResultEnvelope",
    "ResultIssue",
    "ResultOutput",
    "ResultStatus",
    "RetryPolicy",
    "RouteDecision",
    "RouteSource",
    "RouteType",
    "RoutingError",
    "SelectionContext",
    "SelectionDecision",
    "SelectionError",
    "SelectionRejection",
    "SideEffectType",
    "TenantContext",
    "TraceContext",
    "ValueReference",
]
