"""FinanceClaw 业务无关的稳定公共协议。"""

from .approval import (
    ApprovalDecision,
    ApprovalDecisionType,
    ApprovalGrant,
    ApprovalRequest,
)
from .base import ContractModel, JsonPrimitive, JsonValue, MutableContractModel
from .capability import (
    CapabilityCompletionMode,
    CapabilityDescriptor,
    CapabilityExecutionProfile,
    CapabilityType,
    EgressType,
    IdempotencyType,
    SideEffectType,
)
from .context import (
    CancellationContext,
    ExecutionState,
    ExecutionStatus,
    IdentityContext,
    InvocationContext,
    TenantContext,
    TraceContext,
)
from .context_engineering import (
    ContextConsumer,
    ContextFreshness,
    ContextItem,
    ContextOmission,
    ContextOmissionReason,
    ContextProjection,
    ContextProjectionLimits,
    ContextProvenance,
    ContextSensitivity,
    ContextSnapshot,
    ContextSourceKind,
    ContextSourceRef,
    ContextTrustTier,
    ContextUseRecord,
)
from .errors import (
    CapabilityError,
    ContextError,
    ErrorCategory,
    ErrorCode,
    ErrorDetail,
    HarnessError,
    HarnessTimeoutError,
    MemoryAccessError,
    PluginError,
    PolicyError,
    ProviderError,
    RegistryError,
    RequestError,
    SelectionError,
)
from .memory import (
    MemoryKind,
    MemoryProvenance,
    MemoryQuery,
    MemoryRecord,
    MemorySensitivity,
    MemorySlice,
    MemorySubjectScope,
    MemoryWriteDraft,
    MemoryWriteProposal,
)
from .observation import Observation
from .provider import (
    ProviderAttempt,
    ProviderAttemptStatus,
    ProviderDescriptor,
    ProviderHealthSnapshot,
    ProviderHealthStatus,
    ProviderPin,
)
from .request import Request, RequestInput, RequestOptions, RequestTarget
from .result import Continuation, ResultEnvelope, ResultIssue, ResultOutput, ResultStatus
from .retry import RetryPolicy
from .selection import SelectionContext, SelectionDecision, SelectionRejection

__all__ = [
    "ApprovalDecision",
    "ApprovalDecisionType",
    "ApprovalGrant",
    "ApprovalRequest",
    "CancellationContext",
    "CapabilityCompletionMode",
    "CapabilityDescriptor",
    "CapabilityExecutionProfile",
    "CapabilityError",
    "CapabilityType",
    "Continuation",
    "ContractModel",
    "ContextConsumer",
    "ContextError",
    "ContextFreshness",
    "ContextItem",
    "ContextOmission",
    "ContextOmissionReason",
    "ContextProjection",
    "ContextProjectionLimits",
    "ContextProvenance",
    "ContextSensitivity",
    "ContextSnapshot",
    "ContextSourceKind",
    "ContextSourceRef",
    "ContextTrustTier",
    "ContextUseRecord",
    "EgressType",
    "ErrorCategory",
    "ErrorCode",
    "ErrorDetail",
    "ExecutionState",
    "ExecutionStatus",
    "HarnessError",
    "HarnessTimeoutError",
    "IdentityContext",
    "IdempotencyType",
    "InvocationContext",
    "JsonPrimitive",
    "JsonValue",
    "MemoryAccessError",
    "MemoryKind",
    "MemoryProvenance",
    "MemoryQuery",
    "MemoryRecord",
    "MemorySensitivity",
    "MemorySlice",
    "MemorySubjectScope",
    "MemoryWriteDraft",
    "MemoryWriteProposal",
    "MutableContractModel",
    "Observation",
    "PluginError",
    "PolicyError",
    "ProviderAttempt",
    "ProviderAttemptStatus",
    "ProviderDescriptor",
    "ProviderError",
    "ProviderHealthSnapshot",
    "ProviderHealthStatus",
    "ProviderPin",
    "RegistryError",
    "Request",
    "RequestError",
    "RequestInput",
    "RequestOptions",
    "RequestTarget",
    "ResultEnvelope",
    "ResultIssue",
    "ResultOutput",
    "ResultStatus",
    "RetryPolicy",
    "SelectionContext",
    "SelectionDecision",
    "SelectionError",
    "SelectionRejection",
    "SideEffectType",
    "TenantContext",
    "TraceContext",
]
